config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'posts#index', as: 'home'

  get 'about' => 'pages#about', as: 'about'

  resources :posts do
      resources :comments 
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :comments
    validates :title, presence: true,
                        length: {minimum: 5}
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    http_basic_authenticate_with name: "bassam", password:"123", only: [:destroy]

    def create
        @post = Post.find(params[:post_id])
        @comment = @post.comments.create(comment_params)
        redirect_to post_path(@post)
    end

    def destroy
        @post = Post.find(params[:post_id])
        @comment = @post.comments.find(params[:id])
        @comment.destroy
        redirect_to post_path(@post)
    end

    private def comment_params
        params.require(:comment).permit(:username, :body)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    http_basic_authenticate_with name: "bassam", password:"123", except: [:index, :show]

    def index
         @posts = Post.all
    end

    def show
        @post = Post.find(params[:id])
    end

    def new
        @post= Post.new
    end

    def create
        @post = Post.new(post_params)
        if(@post.save)
            redirect_to @post
        else
            render 'new'
        end
    end

    def edit
        @post = Post.find(params[:id])
    end

    def update
        @post = Post.find(params[:id])
        if(@post.update(post_params))
            redirect_to @post
        else
            render 'edit'
        end
    end

    def destroy
        @post = Post.find(params[:id])
        @post.destroy
        redirect_to posts_path 
    end

    private def post_params
        params.require(:posts).permit(:title, :body)
    end
    
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Demo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark ">
      <a class="navbar-brand" href="#">Ruby on Rails</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a><%= link_to "Home", home_path, :style => "color: white;",  :class => "btn" %></a>
          </li>
          <li class="nav-item">
            <a><%= link_to "Create post", new_post_path, :style => "color: white;", :class => "btn" %></a>
          <%# </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
            <div class="dropdown-menu" aria-labelledby="dropdown01">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
          <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
        </form> %>
      </div>
    </nav>
<div class="container">
    <%= yield %>
</div>
  </body>
</html>

app/views/posts/edit.html.erb
<h2>Edit Post</h2>

<%= form_for :posts, url: post_url(@post), method: :patch do |f| %>
    <% if @post.errors.any? %>
        <% @post.errors.full_messages.each do |msg| %>
            <div class="alert alert-danger"><%= msg %></div>
        <% end %>    
    <% end %>
    <p>
        <%= f.label :title %><br>
        <%= f.text_field(:title, {:class => 'form-control'}) %>
    </p>

    <p>
        <%= f.label :body %><br>
        <%= f.text_field(:body, {:class => 'form-control'}) %>
    </p>

    <p>
        <%= f.submit({:class => 'btn btn-primary'}) %>
    </p>

<% end %>

app/views/posts/index.html.erb
<h1>Blog Posts</h1>

<% @posts.each do |post| %>
  <div class="card card-body bg-light mt-4">
    <h3><%= post.title %></h3>
    <p><%= post.body %></p>
    <%= link_to "Read More", post_path(post), :class => 'btn btn-secondary', :style => "width: 7rem;" %>
  </div>
  
<% end %>

app/views/posts/new.html.erb
<h2>Add Post</h2>

<%= form_for :posts, url: posts_url do |f| %>
    <% if @post.errors.any? %>
        <% @post.errors.full_messages.each do |msg| %>
            <div class="alert alert-danger"><%= msg %></div>
        <% end %>    
    <% end %>
    <p>
        <%= f.label :title %><br>
        <%= f.text_field(:title, {:class => 'form-control'}) %>
    </p>

    <p>
        <%= f.label :body %><br>
        <%= f.text_field(:body, {:class => 'form-control'}) %>
    </p>

    <p>
        <%= f.submit({:class => 'btn btn-primary'}) %>
    </p>

<% end %>

app/views/posts/show.html.erb
<div class="card card-body bg-light mt-4">
<h2><%= @post.title %></h2>
<p><%= @post.body %></p>
<hr>
<div class="btn-group">
    <%= button_to "Edit", edit_post_path(@post), :class => 'btn btn-primary', :style=> 'margin-right: 10px;' %>
    <%= button_to "Delete", post_path(@post),
    method: :delete,
    data: { confirm: 'are you sure ?' },
    :class => 'btn btn-danger'  %>
</div>








<br>
<h5>All Comments</h5>
<% @post.comments.each do |comment| %>
    <div class="card card-body bg-light mt-2 ">
        <p><strong><%= comment.username %></strong>: <%= comment.body %>
        <%= link_to '[x]', [comment.post, comment], method: :delete, data: { confirm: 'ara you sure?' } %> </p>
    </div>
<% end %>















<br>
<h5>Comment</h5>
<div class="card card-body bg-light ">
<%= form_for([@post, @post.comments.build]) do |f| %>
    <% if @post.errors.any? %>
        <% @post.errors.full_messages.each do |msg| %>
            <div class="alert alert-danger"><%= msg %></div>
        <% end %>    
    <% end %>
    <p>
        <%= f.label :username %><br>
        <%= f.text_field(:username, {:class => 'form-control'}) %>
    </p>

    <p>
        <%= f.label :body %><br>
        <%= f.text_field(:body, {:class => 'form-control'}) %>
    </p>

    <p>
        <%= f.submit({:class => 'btn btn-primary'}) %>
    </p>

<% end %>
<%= render 'comments/comments' %>
<%= render 'comments/form' %>
</div>
</div>